import React, { useEffect, useMemo, useState } from 'react';
import { IconActivity, IconAlertTriangle, IconCamera, IconCheck, IconCpu, IconGauge, IconLock, IconRoute, IconServer, IconShieldCheck } from '@tabler/icons-react';
import { useLiveRuntime } from './liveRuntime';

const FEEDS=[['A','North Concourse','/feeds/feed-a-clear.mp4'],['B','East Entry','/feeds/feed-b-degraded.mp4'],['C','Garden Gate','/feeds/feed-c-temporal.mp4']];
const DEFAULTS=[{id:'A',name:'North Concourse',operating_mode:'SAFETY',priority:5,minimum_service_fps:.2},{id:'B',name:'East Entry',operating_mode:'PRIORITY',priority:4},{id:'C',name:'Garden Gate',operating_mode:'ADAPTIVE',priority:3}];
const COPY={SAFETY_REQUIREMENT:'Protected safety service was due',MANUAL_OVERRIDE:'Operator override took precedence',REQUIRED_MINIMUM_SERVICE:'Minimum service commitment was due',DETERMINISTIC_PRIORITY_AGE_BASELINE:'Priority and waiting time produced the highest score',ADAPTIVE_DWELL_HOLD:'Selection held to prevent rapid switching'};
const n=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';

export default function App(){
 const r=useLiveRuntime(),[obs,setObs]=useState({}),[busy,setBusy]=useState(null),[error,setError]=useState('');
 useEffect(()=>{if(r.v2Inference?.camera_id)setObs(x=>({...x,[r.v2Inference.camera_id]:r.v2Inference}))},[r.v2Inference]);
 const s=r.v2Snapshot,d=r.v2Decision,cams=s?.cameras?.length?s.cameras:DEFAULTS,model=s?.models?.[0],cap=s?.capacity,active=d?.selected_camera_id;
 const modelId=model?.model_id||'person-yolox-tiny',protectedFps=cap?.protected_required_fps?.[modelId]??.2,safeFps=cap?.model_safe_fps?.[modelId]??model?.safe_throughput_fps??12;
 const candidates=d?.candidates||[],map=useMemo(()=>Object.fromEntries(candidates.map(x=>[x.camera_id,x])),[candidates]);
 const byId=Object.fromEntries(cams.map(x=>[x.id||x.camera_id,x])),overrides=new Set((s?.overrides||[]).map(x=>x.camera_id||x));
 const toggle=async id=>{setBusy(id);setError('');try{await r.override(id,!overrides.has(id))}catch(e){setError(e.message)}finally{setBusy(null)}};
 return <div className="shell">
  <header><div className="brand"><b><IconRoute size={17}/></b>CAHMA <strong>CONTROL</strong></div><nav><a href="#live">Orchestration</a><a href="#policy">Policies</a><a href="#receipt">Decision receipt</a></nav><div className={'live '+(r.connected?'on':'')}><i/>{r.connected?'V2 runtime connected':'Connecting'}</div></header>
  <main>
   <section className="hero"><div><label>Heterogeneous camera orchestration</label><h1>Policy decides first.<br/>Adaptive scoring uses what remains.</h1><p>One resident inference service is shared across three feeds. Safety, overrides and minimum service are enforced before utility and fairness choose the next dispatch.</p></div><aside><span>Current dispatch</span><strong>{active?`Camera ${active}`:'Waiting'}</strong><small>{byId[active]?.name||'No scheduler event yet'}</small></aside></section>
   <section className="status"><Stat icon={<IconShieldCheck/>} k="Capacity" v={cap?.accepted===false?'REJECTED':'ADMITTED'}/><Stat icon={<IconServer/>} k="Resident service" v={model?.resident&&model?.warmed?'1 / 1 warm':'Awaiting model'}/><Stat icon={<IconLock/>} k="Protected commitment" v={`${n(protectedFps,1)} FPS`}/><Stat icon={<IconActivity/>} k="Dispatch class" v={d?.decision_class||'—'}/></section>
   <section className="workspace" id="live"><div><Title title="Live camera policies" text="Policy, adaptive signal and final scheduler rank are shown separately." extra="0.5 decisions/sec"/><div className="cameras">{FEEDS.map(([id,fallback,src])=>{const c=byId[id]||DEFAULTS.find(x=>x.id===id),x=map[id],o=obs[id],selected=id===active,mode=c?.operating_mode||'ADAPTIVE';return <article className={selected?'selected':''} key={id}><div className="camhead"><div><span><IconCamera size={14}/> Camera {id}</span><h3>{c?.name||fallback}</h3></div><em className={'mode '+mode.toLowerCase()}>{mode}</em></div><div className="video"><video src={src} autoPlay muted loop playsInline/><span>{selected?'● Production inference':'○ Light observation'}</span>{o&&<b>{o.person_count} people · {n(o.inference_ms,0)} ms</b>}</div><div className="policy"><span>{mode==='SAFETY'?'Guaranteed service':mode==='PRIORITY'?'Priority weighted':'Utility + fairness'}</span><span>Priority {c?.priority}</span></div><div className="metrics"><Metric k="Adaptive utility" v={n(x?.sage_utility)}/><Metric k="Confidence" v={n(x?.sage_confidence)}/><Metric k="Wait" v={x?.wait_ms!=null?`${n(x.wait_ms/1000,1)}s`:'—'}/><Metric k="Final rank" v={x?.rank?`#${x.rank}`:'—'} rank/></div><div className="action"><small>{COPY[x?.reason_code]||'Waiting for scheduler signal'}</small><button className={overrides.has(id)?'active':''} disabled={busy===id||!r.connected} onClick={()=>toggle(id)}>{busy===id?'Applying…':overrides.has(id)?'Release override':'Take control'}</button></div></article>})}</div>{error&&<p className="error"><IconAlertTriangle size={16}/>{error}</p>}</div>
    <aside className="rail" id="policy"><Panel icon={<IconShieldCheck/>} over="Policy engine" title="Decision hierarchy"><ol>{[['01','Safety requirement','Cannot be displaced by scoring.'],['02','Manual override','Operator intent applies immediately.'],['03','Minimum service','Reserved capacity prevents starvation.'],['04','Priority + context','Importance adjusts eligibility.'],['05','Adaptive utility','Remaining capacity follows value + wait.']].map(x=><li key={x[0]}><b>{x[0]}</b><div><strong>{x[1]}</strong><p>{x[2]}</p></div></li>)}</ol></Panel><Panel icon={<IconCpu/>} over="Resident model pool" title={modelId}><dl><Row k="Provider" v={model?.execution_provider||'DirectML'}/><Row k="State" v="Warm + resident" good/><Row k="Load events" v={model?.load_events??1}/><Row k="Safe throughput" v={`${n(safeFps,0)} FPS`}/></dl></Panel><div className="queues"><div><span>Protected queue</span><b>{candidates.filter(x=>x.decision_class==='PROTECTED').length}</b></div><div><span>Adaptive queue</span><b>{candidates.filter(x=>x.decision_class!=='PROTECTED').length}</b></div></div></aside>
   </section>
   <section className="lower"><article id="receipt"><Title title="Decision receipt" text="Machine-readable explanation of the latest allocation." extra={d?.decision_id||'Awaiting event'}/><div className="receipt"><div><span>Selected route</span><h3>{active?`Camera ${active} → ${d?.selected_model_id||'resident model'}`:'No selection yet'}</h3><p>{COPY[d?.reason_code]||'Waiting for the v2 scheduler.'}</p></div><dl><Row k="Policy mode" v={byId[active]?.operating_mode||'—'}/><Row k="Decision class" v={d?.decision_class||'—'}/><Row k="Selector" v={d?.sage_model||'—'}/><Row k="Fallback used" v={d?.fallback_used==null?'—':d.fallback_used?'Yes':'No'}/><Row k="Scheduler rank" v={map[active]?.rank?`#${map[active].rank}`:'—'}/><Row k="Last inference" v={r.v2Inference?.inference_ms?`${n(r.v2Inference.inference_ms,1)} ms`:'—'}/></dl></div></article><article><Title title="Admission control" text="Protected work is admitted only when capacity can honor it." extra={<IconGauge/>}/><div className="capacity"><div><span>Reserved</span><b>{n(protectedFps,1)} FPS</b></div><div><span>Available</span><b>{n(safeFps,0)} FPS</b></div></div><div className="bar"><i style={{width:`${Math.max(1.5,Math.min(100,protectedFps/safeFps*100))}%`}}/></div><p className="ok"><IconCheck size={15}/>Protected capacity is currently feasible.</p></article></section>
   <section className="evidence"><div><label>Evaluation boundary</label><h2>Review‑1 person-routing evidence</h2><p>These frozen holdout results validate the earlier learned person router. They are not heterogeneous SAGE proof; the live v2 selector reports <b>{d?.sage_model||'its active implementation'}</b>.</p></div><div><Row k="Round robin" v="68.71"/><Row k="Confidence only" v="69.59"/><Row k="Learned scalar router" v="92.80" good/></div></section>
  </main><footer>CAHMA Arena v2 · Edge orchestration console <span><IconActivity size={14}/>Every decision recorded</span></footer>
 </div>
}
function Stat({icon,k,v}){return <div>{icon}<span>{k}</span><b>{v}</b></div>} function Metric({k,v,rank}){return <div className={rank?'rank':''}><span>{k}</span><b>{v}</b></div>} function Title({title,text,extra}){return <div className="title"><div><h2>{title}</h2><p>{text}</p></div><code>{extra}</code></div>} function Panel({icon,over,title,children}){return <section className="panel"><div className="pt"><div><span>{over}</span><h2>{title}</h2></div>{icon}</div>{children}</section>} function Row({k,v,good}){return <div className={good?'good':''}><dt>{k}</dt><dd>{v}</dd></div>}
